SRC = main.cpp
SRC += ../../Chapter3/2_AsyncTaskQueues/IntrusivePtr.cpp ../../Chapter3/2_AsyncTaskQueues/Thread.cpp ../../Chapter3/2_AsyncTaskQueues/tinythread.cpp
SRC += ../1_InitOpenAL/LAL.cpp ../1_InitOpenAL/Timers.cpp

all:
	gcc -O3 -o main.exe $(SRC) -std=c++11 -lstdc++ -I ../../Chapter3/2_AsyncTaskQueues -I ../1_InitOpenAL -I src
