CC = gcc

all:
	$(CC) -o main_MessagePump.exe main_MessagePump.cpp Thread.cpp IntrusivePtr.cpp tinythread.cpp -lstdc++ -std=c++14
	$(CC) -o main_WorkerThread.exe main_WorkerThread.cpp Thread.cpp IntrusivePtr.cpp tinythread.cpp -lstdc++ -std=c++14
