SRC = main.cpp
SRC += ../../Chapter3/2_AsyncTaskQueues/IntrusivePtr.cpp 
SRC += src/FileSystem.cpp src/Archive.cpp src/libcompress.c

all:
	gcc -o main.exe $(SRC) -std=c++11 -lstdc++ -I ../../Chapter3/2_AsyncTaskQueues -I src
